# If you intended to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 90.0.1.70
  port: "22"
#  internal_address: 10.244.0.10 change it>
  internal_address: 90.0.1.70
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 90.0.1.71
  port: "22"
#  internal_address: 10.244.0.11 change it>
  internal_address: 90.0.1.71
  role:
  - worker
  - etcd
  hostname_override: ""
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 90.0.1.72
  port: "22"
#  internal_address: 10.244.0.12 change it>
  internal_address: 90.0.1.72
  role:
  - worker
  - etcd
  hostname_override: ""
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.244.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.244.0.0/16
    service_cluster_ip_range: 10.244.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: localdomain.local
    infra_container_image: ""
    cluster_dns_server: 10.244.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: flannel
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: 90.0.1.77:5000/rancher/mirrored-coreos-etcd:v3.4.16-rancher1
  alpine: 90.0.1.77:5000/rancher/rke-tools:v0.1.78
  nginx_proxy: 90.0.1.77:5000/rancher/rke-tools:v0.1.78
  cert_downloader: 90.0.1.77:5000/rancher/rke-tools:v0.1.78
  kubernetes_services_sidecar: 90.0.1.77:5000/rancher/rke-tools:v0.1.78
  kubedns: 90.0.1.77:5000/rancher/mirrored-k8s-dns-kube-dns:1.17.4
  dnsmasq: 90.0.1.77:5000/rancher/mirrored-k8s-dns-dnsmasq-nanny:1.17.4
  kubedns_sidecar: 90.0.1.77:5000/rancher/mirrored-k8s-dns-sidecar:1.17.4
  kubedns_autoscaler: 90.0.1.77:5000/rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  coredns: 90.0.1.77:5000/rancher/mirrored-coredns-coredns:1.8.4
  coredns_autoscaler: 90.0.1.77:5000/rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  nodelocal: 90.0.1.77:5000/rancher/mirrored-k8s-dns-node-cache:1.18.0
  kubernetes: 90.0.1.77:5000/rancher/hyperkube:v1.21.5-rancher1
  flannel: 90.0.1.77:5000/rancher/mirrored-coreos-flannel:v0.14.0
  flannel_cni: 90.0.1.77:5000/rancher/flannel-cni:v0.3.0-rancher6
  calico_node: 90.0.1.77:5000/rancher/mirrored-calico-node:v3.19.2
  calico_cni: 90.0.1.77:5000/rancher/mirrored-calico-cni:v3.19.2
  calico_controllers: 90.0.1.77:5000/rancher/mirrored-calico-kube-controllers:v3.19.2
  calico_ctl: 90.0.1.77:5000/rancher/mirrored-calico-ctl:v3.19.2
  calico_flexvol: 90.0.1.77:5000/rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
  canal_node: 90.0.1.77:5000/rancher/mirrored-calico-node:v3.19.2
  canal_cni: 90.0.1.77:5000/rancher/mirrored-calico-cni:v3.19.2
  canal_controllers: 90.0.1.77:5000/rancher/mirrored-calico-kube-controllers:v3.19.2
  canal_flannel: 90.0.1.77:5000/rancher/mirrored-coreos-flannel:v0.14.0
  canal_flexvol: 90.0.1.77:5000/rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
  weave_node: 90.0.1.77:5000/weaveworks/weave-kube:2.8.1
  weave_cni: 90.0.1.77:5000/weaveworks/weave-npc:2.8.1
  pod_infra_container: 90.0.1.77:5000/rancher/mirrored-pause:3.4.1
  ingress: 90.0.1.77:5000/rancher/nginx-ingress-controller:nginx-0.48.1-rancher1
  ingress_backend: 90.0.1.77:5000/rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  ingress_webhook: 90.0.1.77:5000/rancher/mirrored-jettech-kube-webhook-certgen:v1.5.1
  metrics_server: 90.0.1.77:5000/rancher/mirrored-metrics-server:v0.5.0
  windows_pod_infra_container: 90.0.1.77:5000/rancher/kubelet-pause:v0.1.6
  #aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  #aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  #aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  #aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  #aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  #aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  #aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  #aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: none
  options: {}
ignore_docker_version: null
enable_cri_dockerd: null
kubernetes_version: ""
private_registries:
  - url: 90.0.1.77:5000
    user: root
    password: root
    is_default: true 
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null

