---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpd
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: cube-node2.mydomain
      http:
        paths:
          - backend:
              serviceName: httpd
              servicePort: 80